import { useState } from 'react'
import { useEvents, useLive, useRul } from './useLive'
import { Badge, HealthGauge, Panel, STATE, SubsystemBars, stateFor } from './components/Panels'
import {
  ActionPanel, Channel, EventLog, Evidence, HealthTrend, RulPanel, SourceBar,
} from './components/Telemetry'
import { CameraFeed, DigitalTwin } from './components/Twin'
import { PulseOnChange, Reveal, Trend } from './components/motion'
import { Aurora, GlassFilters } from './components/Glass'

function Header({
  connected, state, paused, onPause, simulated,
}: {
  connected: boolean
  state: keyof typeof STATE
  paused: boolean
  onPause: () => void
  simulated: boolean
}) {
  const s = STATE[state]
  return (
    <header className="glass relative z-20 flex shrink-0 flex-wrap items-center gap-x-5 gap-y-2 px-5 py-3"
            style={{ borderRadius: 0, boxShadow: 'inset 0 -1px 0 rgba(255,255,255,0.09), 0 8px 32px -20px rgba(0,0,0,0.9)' }}>
      <div className="flex items-center gap-2.5">
        <svg width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden>
          <rect x="1.5" y="8.5" width="21" height="7" rx="3.5"
                stroke="var(--color-info)" strokeWidth="1.6" />
          <path d="M12 8.5v7" stroke="var(--color-info)" strokeWidth="1.6" strokeLinecap="round" />
          <circle cx="6" cy="12" r="1.2" fill="var(--color-info)" />
          <circle cx="18" cy="12" r="1.2" fill="var(--color-info)" />
        </svg>
        <div className="leading-tight">
          <h1 className="text-[16px] font-600 tracking-[-0.02em]">BeltGuard</h1>
          <p className="text-[9.5px] font-500 tracking-[0.12em] text-[var(--color-fg-dim)] uppercase">
            NMDC Line A · Conveyor CV-204
          </p>
        </div>
      </div>

      {/* Status is the loudest thing in the room, and never colour-only.
          It pulses on change so an escalation registers even if the operator
          was looking at another panel when it happened. */}
      <PulseOnChange trigger={state} color={`color-mix(in srgb, ${s.color} 55%, transparent)`}>
        <div className="flex items-center gap-2 rounded-full px-3.5 py-1.5"
             style={{ background: `color-mix(in srgb, ${s.color} 16%, transparent)`,
                      boxShadow: `inset 0 0 0 0.5px color-mix(in srgb, ${s.color} 60%, transparent),
                                  inset 0 1px 0 color-mix(in srgb, ${s.color} 35%, transparent),
                                  0 0 22px -6px ${s.color}` }}>
          <span aria-hidden style={{ color: s.color }} className="text-[10px]">{s.glyph}</span>
          <span className="text-[12px] font-600 tracking-[0.1em]" style={{ color: s.color }}>
            {s.label}
          </span>
        </div>
      </PulseOnChange>

      <div className="ml-auto flex items-center gap-2">
        {simulated && (
          <Badge tone="warn" title="Sensor streams are generated by the simulator, not read from hardware">
            simulated data
          </Badge>
        )}
        <span className="flex items-center gap-1.5 text-[10px] text-[var(--color-fg-muted)]">
          <span className="relative inline-flex h-1.5 w-1.5 rounded-full"
                style={{ background: connected ? 'var(--color-ok)' : 'var(--color-crit)',
                         color: connected ? 'var(--color-ok)' : 'var(--color-crit)' }}>
            {connected && !paused && <span className="live-dot" />}
          </span>
          {connected ? (paused ? 'PAUSED' : 'LIVE') : 'DISCONNECTED'}
        </span>
        {/* Required by the streaming-chart guidance: the operator must be able
            to stop the view moving to read a value. */}
        <button onClick={onPause}
                className="cursor-pointer rounded-full px-3.5 py-1.5 text-[10px] font-600 tracking-[0.08em] text-[var(--color-fg-muted)] uppercase transition-all duration-200 hover:text-[var(--color-fg)] focus-visible:ring-2 focus-visible:ring-[var(--color-info)] focus-visible:outline-none"
                style={{ background: 'rgba(255,255,255,0.09)',
                         boxShadow: 'inset 0 0 0 0.5px rgba(255,255,255,0.18), inset 0 1px 0 rgba(255,255,255,0.22)' }}>
          {paused ? 'Resume' : 'Pause'}
        </button>
      </div>
    </header>
  )
}

function Empty() {
  return (
    <div className="flex flex-1 items-center justify-center p-8">
      <div className="glass max-w-lg px-8 py-7 text-center">
        <h2 className="text-[19px] font-600 tracking-[-0.02em]">Waiting for telemetry</h2>
        <p className="mt-2 text-[12px] leading-relaxed text-[var(--color-fg-muted)]">
          No sensor data on the bus yet. Start the three services:
        </p>
        <pre className="tnum plate mt-4 overflow-x-auto p-4 text-left text-[11px] leading-relaxed text-[var(--color-info)]">
{`python infra/broker.py
python -m uvicorn backend.app:app --port 8010
python -m sensors_sim.run`}
        </pre>
      </div>
    </div>
  )
}

export default function App() {
  const [paused, setPaused] = useState(false)
  const { frame, series, connected } = useLive(paused)
  const rul = useRul(connected)
  const { events, smtp } = useEvents(connected)

  const health = frame?.health
  const state = stateFor(health?.overall)
  const simulated = Object.values(health?.sources ?? {}).some((s) => s.simulated)

  // CRITICAL puts a slow breathing red edge on the whole viewport -- readable
  // from across a room, which is the actual condition of a control room.
  return (
    <div className={`relative flex h-full flex-col ${state === 'CRITICAL' ? 'alarm-critical' : ''}`}>
      <Aurora />
      <GlassFilters />
      <Header connected={connected} state={state} paused={paused}
              onPause={() => setPaused((p) => !p)} simulated={simulated} />

      {!frame ? (
        <Empty />
      ) : (
        <main className="relative z-10 flex flex-1 flex-col gap-3 overflow-auto p-3
                         lg:grid lg:min-h-0 lg:grid-cols-[312px_minmax(0,1fr)_324px]
                         lg:overflow-hidden">
          {/* LEFT: state at a glance */}
          <div className="flex flex-col gap-3 lg:min-h-0 lg:overflow-y-auto">
            <Reveal index={0}><Panel title="Belt Health"
                   right={<Badge tone={state === 'NORMAL' ? 'ok' : state === 'WARNING' ? 'warn' : 'crit'}>
                     {STATE[state].label}</Badge>}>
              <HealthGauge score={health!.overall} state={state} />
            </Panel></Reveal>
            <Reveal index={1}><Panel title="Subsystems">
              <SubsystemBars subsystems={health!.subsystems} />
            </Panel></Reveal>
            <Reveal index={2}><Panel title="Predicted Life">
              <RulPanel rul={rul} />
            </Panel></Reveal>
            <Reveal index={3} className="lg:flex-1">
              <Panel title="Recommended Action" className="h-full">
                <ActionPanel health={health!} rul={rul} />
              </Panel>
            </Reveal>
          </div>

          {/* CENTRE: the belt itself */}
          <div className="flex flex-col gap-3 lg:min-h-0 lg:overflow-y-auto">
            <Reveal index={1} className="min-h-[230px] lg:flex-[1.15]">
            <Panel title="Digital Twin" solid
                   right={<span className="tnum text-[10px] text-[var(--color-fg-dim)]">
                     {(frame.readings?.speed?.speed_mps ?? 0).toFixed(2)} m/s</span>}
                   className="h-full">
              <DigitalTwin frame={frame} />
            </Panel></Reveal>

            <Reveal index={2}><Panel title="Health Trend"
                   right={<div className="flex items-center gap-2">
                     <Trend value={health!.overall} />
                     {rul?.hours_to_critical ? <Badge tone="warn">projection</Badge> : null}
                   </div>}>
              <HealthTrend series={series} rul={rul} />
            </Panel></Reveal>

            <Reveal index={3} className="grid shrink-0 grid-cols-2 gap-3 xl:grid-cols-4">
              <Channel series={series} label="Vibration RMS" unit="mm/s" color="var(--color-info)"
                       warn={2.8} pick={(f) => f.readings?.vibration?.rms_mm_s} />
              <Channel series={series} label="Kurtosis" unit="" color="#a78bfa" warn={6}
                       pick={(f) => f.readings?.vibration?.kurtosis} />
              <Channel series={series} label="Bearing Temp" unit="°C" color="var(--color-warn)"
                       warn={70} digits={1} pick={(f) => f.readings?.temperature?.temp_c} />
              <Channel series={series} label="Belt Tension" unit="kN" color="var(--color-ok)"
                       digits={1} pick={(f) => f.readings?.load?.tension_kn} />
            </Reveal>
          </div>

          {/* RIGHT: camera + why */}
          <div className="flex flex-col gap-3 lg:min-h-0 lg:overflow-y-auto">
            <Reveal index={2} className="min-h-[220px] lg:flex-[0.9]">
              <Panel title="Inspection Camera" className="h-full"
                     right={<Badge tone={health!.vision_active ? 'ok' : 'neutral'}>
                       {health!.vision_active ? 'detecting' : 'offline'}</Badge>}>
                <CameraFeed frame={frame} />
              </Panel>
            </Reveal>
            <Reveal index={3} className="min-h-[160px] lg:flex-1">
              <Panel title="Active Indicators" className="h-full"
                     right={<Badge>{health!.reasons.length}</Badge>}>
                <Evidence reasons={health!.reasons} />
              </Panel>
            </Reveal>
            <Reveal index={4} className="min-h-[140px] lg:flex-[0.8]">
              <Panel title="Event Log" className="h-full"
                     right={<Badge>{events.length}</Badge>}>
                <EventLog events={events} smtp={smtp} />
              </Panel>
            </Reveal>
            <Panel title="Data Sources">
              <SourceBar frame={frame} />
            </Panel>
          </div>
        </main>
      )}
    </div>
  )
}
